In [4]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

data = pd.read_csv('/home/paradox/Code/Neural Network/train.csv')

In [5]:
data.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [6]:
data.shape


(42000, 785)

In [7]:
data = np.array(data)
m, n = data.shape

In [8]:
np.random.shuffle(data) #shuffling for test and train split

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev/255



In [9]:
Y_dev

array([2, 2, 5, 1, 0, 0, 3, 7, 2, 2, 0, 1, 0, 6, 7, 5, 8, 2, 9, 1, 0, 6,
       6, 0, 6, 4, 3, 7, 6, 3, 8, 7, 3, 3, 7, 5, 7, 9, 5, 2, 6, 3, 1, 0,
       1, 3, 3, 5, 6, 6, 1, 4, 9, 0, 8, 6, 0, 5, 9, 3, 0, 5, 0, 3, 4, 8,
       8, 6, 4, 5, 7, 3, 1, 2, 1, 9, 2, 0, 2, 5, 3, 6, 9, 4, 3, 3, 8, 1,
       3, 6, 1, 2, 3, 4, 9, 7, 8, 8, 7, 4, 2, 2, 4, 1, 5, 7, 7, 2, 0, 2,
       7, 7, 7, 6, 7, 3, 0, 6, 8, 6, 5, 0, 0, 3, 3, 9, 1, 1, 4, 2, 7, 4,
       7, 5, 0, 0, 1, 1, 1, 2, 2, 9, 0, 2, 4, 6, 9, 4, 3, 3, 4, 8, 3, 4,
       7, 3, 4, 2, 8, 6, 9, 0, 5, 3, 8, 2, 0, 1, 4, 9, 1, 6, 0, 1, 1, 4,
       3, 9, 3, 1, 0, 6, 9, 7, 6, 8, 3, 4, 1, 2, 7, 8, 5, 6, 9, 4, 0, 8,
       4, 9, 8, 4, 6, 1, 2, 1, 6, 3, 1, 2, 2, 0, 5, 7, 5, 4, 1, 0, 2, 2,
       7, 5, 3, 5, 9, 4, 9, 0, 9, 1, 6, 4, 5, 8, 9, 6, 3, 6, 5, 5, 2, 7,
       3, 2, 4, 1, 1, 7, 2, 3, 9, 3, 3, 6, 8, 1, 4, 5, 5, 7, 0, 7, 2, 3,
       7, 3, 7, 0, 2, 3, 5, 0, 7, 1, 9, 8, 6, 4, 1, 1, 3, 7, 1, 0, 2, 3,
       5, 9, 4, 8, 8, 8, 1, 7, 8, 3, 2, 8, 2, 5, 1,

In [10]:
Y_dev.shape

(1000,)

In [11]:
X_dev.shape

(784, 1000)

In [12]:
Y_dev.shape
X_dev.shape

(784, 1000)

In [13]:
data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train/255
_, m_train = X_train.shape

In [14]:
m_train

41000

In [15]:
Y_train

array([5, 3, 4, ..., 0, 6, 2], shape=(41000,))

In [16]:
Y_train.shape, X_train.shape

((41000,), (784, 41000))

In [17]:
def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5

    return W1, b1, W2, b2

In [18]:
def ReLU(Z):
    return np.maximum(Z, 0)

def softmax(Z):
    return np.exp(Z)/sum(np.exp(Z)) #takes in the vector and return the operation element wise

def ReLU_deriv(Z):
    return Z>0


In [19]:
def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

In [20]:
def one_hot(Y): #explain this all
    one_hot_Y = np.zeros((Y.size, Y.max()+1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

In [21]:
def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1/m * dZ2.dot(A1.T)
    db2 = 1/m * np.sum(dZ2)
    dZ1  = W2.T.dot(dZ2)* ReLU_deriv(Z1)
    dW1 = 1/m * dZ1.dot(X.T)
    db1 = 1/m * np.sum(dZ1)
    return dW1, db1, dW2, db2

In [22]:
def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1
    W2 = W2 - alpha * dW2
    b2 = b2 - alpha * db2
    return W1, b1, W2, b2


In [23]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y)/Y.size

In [25]:
def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)

        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2

In [27]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 0.10, 501)

Iteration:  0
[1 0 0 ... 0 0 1] [5 3 4 ... 0 6 2]
0.06658536585365854
Iteration:  10
[2 8 6 ... 0 2 2] [5 3 4 ... 0 6 2]
0.18621951219512195
Iteration:  20
[0 2 6 ... 0 6 2] [5 3 4 ... 0 6 2]
0.2929024390243902
Iteration:  30
[0 2 4 ... 0 6 2] [5 3 4 ... 0 6 2]
0.3655609756097561
Iteration:  40
[0 2 4 ... 0 6 2] [5 3 4 ... 0 6 2]
0.4239512195121951
Iteration:  50
[0 2 4 ... 0 6 2] [5 3 4 ... 0 6 2]
0.47185365853658534
Iteration:  60
[0 2 4 ... 0 6 2] [5 3 4 ... 0 6 2]
0.5167804878048781
Iteration:  70
[0 2 4 ... 0 6 2] [5 3 4 ... 0 6 2]
0.5546829268292683
Iteration:  80
[0 2 4 ... 0 6 2] [5 3 4 ... 0 6 2]
0.5880731707317073
Iteration:  90
[0 2 4 ... 0 6 2] [5 3 4 ... 0 6 2]
0.6153170731707317
Iteration:  100
[0 2 4 ... 0 6 2] [5 3 4 ... 0 6 2]
0.6386829268292683
Iteration:  110
[0 2 4 ... 0 6 2] [5 3 4 ... 0 6 2]
0.6594878048780488
Iteration:  120
[0 2 4 ... 0 6 2] [5 3 4 ... 0 6 2]
0.6765853658536586
Iteration:  130
[0 2 4 ... 0 6 2] [5 3 4 ... 0 6 2]
0.6920487804878048
Iteration:  14